
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA FROM ID SELECT STARquery : select_stmtselect_stmt : SELECT select_list FROM IDselect_list : STARselect_list : column_listcolumn_list : IDcolumn_list : column_list COMMA ID'
    
_lr_action_items = {'SELECT':([0,],[3,]),'$end':([1,2,10,],[0,-1,-2,]),'STAR':([3,],[6,]),'ID':([3,8,9,],[5,10,11,]),'FROM':([4,5,6,7,11,],[8,-5,-3,-4,-6,]),'COMMA':([5,7,11,],[-5,9,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'query':([0,],[1,]),'select_stmt':([0,],[2,]),'select_list':([3,],[4,]),'column_list':([3,],[7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> query","S'",1,None,None,None),
  ('query -> select_stmt','query',1,'p_query','parser.py',25),
  ('select_stmt -> SELECT select_list FROM ID','select_stmt',4,'p_select_stmt','parser.py',29),
  ('select_list -> STAR','select_list',1,'p_select_list_star','parser.py',34),
  ('select_list -> column_list','select_list',1,'p_select_list_column_list','parser.py',38),
  ('column_list -> ID','column_list',1,'p_column_list_single','parser.py',42),
  ('column_list -> column_list COMMA ID','column_list',3,'p_column_list_multiple','parser.py',46),
]
